apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-myapp
  labels:
    appname: mvp-myapp
spec:
  selector:
    matchLabels:
      appname: mvp-myapp
  replicas: 1
  template:
    metadata:
      name: mvp-myapp
      labels:
        appname: mvp-myapp
    spec:
      containers:
      - name: mvp-myapp
        image: mycluster.icp:8500/ostrich/testimage
        imagePullPolicy: Always
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: config-myapp
                key: PORT
        ports:
          - name: port1
            containerPort: 8081
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
